DROP DATABASE IF EXISTS sweat_itDB;
CREATE DATABASE sweat_itDB;

USE sweat_itDB;

CREATE TABLE users(
  id INT NOT NULL AUTO_INCREMENT,
  pass VARCHAR(100) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE exercises(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
);
